nodeLinker: node-modules
enableGlobalCache: true
npmRegistryServer: "https://registry.npmjs.org"

# Build settings
enableScripts: true
preferInteractive: true
enableTelemetry: false
nmMode: hardlinks-local

# Installation settings
checksumBehavior: "update"
compressionLevel: "mixed"

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard
  - code: YN0013
    level: discard
  - code: YN0032
    level: discard
  - code: YN0061
    level: discard
  - code: YN0065
    level: discard

packageExtensions:
  deasync@*:
    dependencies:
      node-gyp: ^9.0.0
  cypress@*:
    dependencies:
      node-gyp: ^9.0.0 