version: '3.7'
services:
  mermaid:
    build:
      context: .
      target: mermaid-dev
    volumes:
      - ./src:/app/src
    ports:
      # Maps host port 3008 to container port 3000
      - 3008:3008
      - 24678:24678
