[build]
command = "corepack enable && yarn install && yarn build"
publish = ".svelte-kit/cloudflare"

[build.environment]
NODE_VERSION = "18"
YARN_ENABLE_IMMUTABLE_INSTALLS = "false"

[env.production]
MERMAID_ANALYTICS_URL = "https://p.mermaid.live"
MERMAID_DOMAIN = "mermaid.live"
MERMAID_RENDERER_URL = "https://mermaid.ink"
MERMAID_KROKI_RENDERER_URL = "https://kroki.io"
MERMAID_IS_ENABLED_MERMAID_CHART_LINKS = "true" 